### ISSUE TITLE
Transitive `fs-extra` dependencies in `storybook`

### ISSUE THREAD

**Issue by pralkarz** [43081j/ecosystem-cleanup#113]
After opening https://github.com/storybookjs/storybook/pull/29126, I decided to check what would be needed to completely remove `fs-extra` from the repository. Here are the transitive dependencies that use it (also a few more replacements we could try to make there).

- [ ] [nx/js](https://github.com/nrwl/nx/blob/dc821abd5249bb2769c58e3d9f466bd67bb516fa/packages/js/package.json#L51) – `chalk`, `fast-glob`, ~`fs-extra`~ (https://github.com/nrwl/nx/pull/27932). Also tracked in #117.
- [ ] [@storybook/bench](https://github.com/storybookjs/bench/blob/cd16744cc615a0221e8310226c37e9dc4e0b3e5b/package.json#L45) – `fs-extra`. The repo is archived, so not sure if it can be tackled in any way.
- [ ] [file-system-cache](https://github.com/philcockfield/file-system-cache/blob/b527be360c65cc6392f9d969b51f5063810628e3/package.json#L47) – `fs-extra`.
- [ ] [fork-ts-checker-webpack-plugin](https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/blob/0fab463b21c6edc4d94834568a3f440241d57887/package.json#L63) – supports Node >=12; `chalk`, `chokidar` (3 -> 4), `fs-extra`, potentially `node-abort-controller`.
- [ ] [broccoli-output-wrapper](https://github.com/broccolijs/broccoli-output-wrapper/blob/f9876eabb7f484669d2338bb747da77d697080ba/package.json#L16) – just `fs-extra`, but might not be feasible since it supports Node 10 and >= 12.
- [ ] [fs-merger](https://github.com/broccolijs/fs-merger/blob/91e382d9bfff1fa9a9f3a20009fd8f21f39c4d2c/package.json#L48) – `fs-extra`. Potentially could also replace `walk-sync` with `empathic`.
- [ ] [fast-sourcemap-concat](https://github.com/ef4/fast-sourcemap-concat/blob/dba9de6fc8785acfeab4a68285c86d833c6e1cc1/package.json#L18) – `chalk` and `fs-extra`, but might not be feasible since it supports Node 10 and >= 12.
- [ ] [broccoli-concat](https://github.com/broccolijs/broccoli-concat/blob/8c35038f012f57c791f7c9ad370a54b467e0e0cc/package.json#L31) – `fs-extra` and a few `lodash`es, but might not be feasible since it supports Node 10 and >= 12.
- [ ] [fixturify](https://github.com/joliss/node-fixturify/blob/46818777755d4f7246a4a919e08a32f7a7d6f6b1/package.json#L16) – `fs-extra`. Potentially could also replace `walk-sync` with `empathic`.
- [ ] [nx](https://github.com/nrwl/nx/blob/dc821abd5249bb2769c58e3d9f466bd67bb516fa/packages/nx/package.json#L55) – `chalk`, ~`fs-extra`~ (https://github.com/nrwl/nx/pull/28019), `ora`. Also tracked in #117.
- [ ] [vite-plugin-inspect](https://github.com/antfu-collective/vite-plugin-inspect/blob/a9176a8f2ddb4db89236754edbdb4bf26b0761b4/package.json#L87) – `fs-extra`.
